fix: Set correct version on module root
terraform-aws-modules/terraform-aws-acm pull request #126
Opened 2022-12-05 00:43 UTC by bryantbiggs

## Description
- Set correct version on module root

## Motivation and Context
- The root version was not updated in https://github.com/terraform-aws-modules/terraform-aws-acm/pull/125

## Breaking Changes
- No

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2022-12-05 14:02 UTC, sub2zero approved these changes

2022-12-05 14:04 UTC, sub2zero requested changes
looks good to me

2022-12-08 14:36 UTC, antonbabenko approved these changes

2022-12-08 14:37 UTC, merged

2022-12-08 14:38 UTC, antonbabenko commented
This PR is included in version 4.3.1 :tada: