feat: Allow multiple domains in one cert
terraform-aws-modules/terraform-aws-acm pull request #137
Opened 2023-09-13 20:58 UTC by amontalban

## Description
This PR allows creating one ACM certificate for multiple domains, which, is useful when using the certificate for CloudFront that only allows one certificate per distribution.

## Motivation and Context
CloudFront does not support multiple ACM certificates, like ALB. Therefore, if you need to support multiple domains in a single CloudFront distribution you would have to create the certificate manually because this module does not support it.

## Breaking Changes
This change should be backward compatible as I added a `zones` var containing a map with domains and their Route53 zone ID so the validation records are created in the correct Route53 zone.

Additionally, I have updated the tests in `examples/complete-dns-validation` to allow variables so it was easier for me (and others) to test with my test domains.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

2023-10-06 14:04 UTC, amontalban commented
@antonbabenko Do you think this is good to be merged? I have tested with my use case but I don't have access to the zones/domains that are described in the test cases so cannot fully validate it is a breaking change or not.

Thank you!

2023-10-06 15:20 UTC, antonbabenko requested changes
It looks pretty good, but small updates are necessary. Please make examples 100% working and verify them yourself (for e.g., by providing your own domain names via `terraform.tfvars`). Also, set required `validation_method` argument.

Also, update main README.md and include code snippet for multi-domain ACM in the same fashion as with other snippets.

2023-10-06 15:20 UTC, antonbabenko commented on examples/complete-dns-validation/main.tf
> +  region = local.region
Please revert all changes not necessary for your PR.

2023-10-06 15:20 UTC, antonbabenko commented on examples/complete-dns-validation/main.tf
> +  region = local.region
Please remove `region` as it is not important for this example.

2023-10-06 15:20 UTC, antonbabenko commented on examples/complete-dns-validation/main.tf
> +  region = "us-east-1"
Please remove this `region`, too.

2023-10-06 15:20 UTC, antonbabenko commented on examples/complete-dns-validation/variables.tf
> +  description = "Extr adomain to be used for the tests"
```suggestion
  description = "Extra domain to be used in acm_multi_domain module"
```

2023-11-02 02:54 UTC, vishwa-trulioo commented
Any update on this merge?

2023-11-02 12:25 UTC, bryantbiggs commented
changes have been requested but not implemented as shown above, so it won't be merged until resolved

2023-12-14 00:06 UTC, closed without merging